apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-app-deployment
  labels:
    app: minikube-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minikube-app
  template:
    metadata:
      labels:
        app: minikube-app
    spec:
      containers:
      - name: minikube-app
        image: agassner/minikube-app:latest
        ports:
        - containerPort: 8080